services:
  - type: web
    name: supermarket-billing
    runtime: docker

    plan: free

    branch: main

    dockerfilePath: ./Dockerfile

    autoDeploy: true

    healthCheckPath: /

    envVars:
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"