# Application Name
spring.application.name=superMarketBilling

# Server Port
server.port=${PORT:8080}

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d9d1jhmrnols73clqrc0-a.singapore-postgres.render.com:5432/super_market_db_3fkt
spring.datasource.username=super_market_db_3fkt_user
spring.datasource.password=U5vrGLjzEOWXD6abR5WXaijPjx2LzFZx
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect